a = "Mouse"
print("-----INDEXING-----")
print(a[0])
print(a[1])
print(a[-3])
print(a[-2])
print(a[-1])
print("-------SLICING--------")
print(a[:4])
print(a[1:4])
print(a[1:-2])
print(a[:-1])
print(a[::-1])
print(a[:-2])
print(a[:-3])
print("-------STRING FUNCTIONS-------")
print(a.capitalize())
print(a.upper())
print(a.lower())
b = "keYboArD"
print(b.swapcase())
c = "hello welcome "
print(c.title())
print(c.count("e"))
print(a.isalpha())
print(a.islower())
print(a.isupper())
print(a.isalnum())
print(c.index("welcome"))
print(c.find("hello"))
print(a+b+c)
print(len(a))